name: Test
on:
  push:
    branches-ignore:
      - 'develop'
      - 'gh-pages'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir data || true
      - run: npm install
      - name: Test
        run: npm test
